In [2]:
import numpy as np
import math

# Exercise 1

Tạo 1 array 1 chiều gồm 26 phần tử

Tách array thành 4 array con, sao cho các array con đều nhau nhất có thể (về số lượng)

coi 26 là hằng số (tính toán với nó được)
KHông chơi hardcode (split theo index định nghĩa sẵn)

In [17]:
def find_sub_arr(n,s):
    # n : số phần tử của mảng khởi tạo
    # s: số lượng mảng con cần chia
    l = [] #danh sách chứa số lượng phần tử của từng mảng con
    if n % s == 0:
        l.append(int(n/s))
        return l * s
    else: 
        a = math.floor(n/s) 
        b = math.ceil(n/s)          
        num_b = n - s * a  
        num_a = s - num_b 
    for i in range(num_a):
        l.append(a)
    for j in range(num_b):
        l.append(b)
    return l


arr = np.arange(26)
num_sub_arr = 4
print(arr)
print(" The nummer of elements in each sub array is :" , find_sub_arr(len(arr),num_sub_arr))



[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25]
 The nummer of elements in each sub array is : [6, 6, 7, 7]


# Exercise 2

Cho ma trận A kích thước 2000*1000
Cho vector B có chiều dài 1000, giá trị của từng element 1 -> 1000
Yêu cầu: Với mỗi hàng ở trong A, lấy ra cột được xác định trong B

Ví dụ:

b[0] = 440

Thì hàng 0 của a -> lấy giá trị của cột thứ 440

b[1] = 750

Thì hàng 1 của a -> lấy giá trị của cột thứ 750

Kết qủa là 1 vector cùng chiều với B

In [153]:
a = np.random.randint(1,10000, (2000,1000))
a

array([[9514, 7814, 4409, ..., 4389, 1315, 7901],
       [1626, 7004, 7849, ..., 3077, 2054, 6702],
       [ 667, 6289,  297, ..., 2506, 2455, 2089],
       ...,
       [1028, 9615, 5847, ..., 8673, 1184, 4248],
       [5734, 3969, 2588, ..., 9155, 8776, 3385],
       [2031, 1065,  887, ..., 7904, 1339, 9478]])

In [154]:
b = np.random.randint(0,999,1000)
b

array([697, 941, 757, 152, 981, 985, 255, 393, 222, 943, 995,  46, 456,
        71,  69, 566, 919, 580, 748, 623, 509, 820, 353, 257, 334, 208,
       586, 973, 685, 761, 212, 594, 501, 383, 200, 798, 660, 467, 821,
       699, 855, 655, 101, 195, 313, 374, 107, 843, 113, 797, 353, 355,
       827, 447, 353,   5, 625, 172, 284,  75, 706, 715, 272, 627, 285,
       873, 849, 929, 267, 216, 988,  27, 323,  65, 965, 789, 791, 524,
       403, 619, 780, 576, 373,  96, 132, 929, 818, 547, 209, 407, 222,
       438, 678, 359, 983, 721, 851, 449, 426, 553, 171, 200, 505, 178,
       667, 337, 121, 745,  89, 547,  52, 783, 607, 291, 152, 181, 343,
       373,  42, 601, 698, 107, 447, 870, 392, 491, 241, 681, 438, 821,
       370, 584, 269, 106, 965,  72, 141,  15, 862, 194, 793, 656, 527,
       905, 319, 331, 618, 651, 913, 396, 182, 874, 761, 372, 186, 639,
       625, 988, 814, 841,   2, 684, 779, 885, 401, 607, 369, 563, 657,
       289,  67, 409, 756, 400, 560, 595, 916, 537, 737, 804, 37

In [156]:
b.shape

(1000,)

In [155]:
new_list= []
for i in range(len(b)):   
    c = b[i]
    d = a[i,c]
    new_list.append(d)
new_arr = np.array(new_list)
new_arr

array([ 680, 2181, 4280, 5555, 1706, 3667, 7626, 4939, 6789, 7628,  137,
        355, 5678, 7539, 7304, 7510, 1388, 7531, 3428, 6262,  116, 2885,
       5422, 8318, 7487, 8602, 7513, 2354, 1318, 1928, 6850, 3503, 1122,
       3849, 9796, 3823, 8754, 4741, 2757,  705, 8460, 2724, 9164, 8579,
       5678, 4269, 2333, 8430, 9555, 7562, 5013, 5745, 4525, 1154, 2477,
       3875, 4580, 3794, 6717,  910, 5701, 4275, 4963,  248, 9187, 6813,
         51, 7660, 3750, 1427, 4741, 5925, 3631, 8340,  189, 3601, 1084,
       1395, 5994,  178, 1939, 8086, 9874, 1671, 8244, 1337, 2283, 7984,
       6454, 4714, 8399, 9928, 4418, 3552, 8173, 5470, 5789, 7695, 5268,
       5173, 6000, 3816, 6100, 6747, 9518,   31,  642,   36, 2947, 8061,
       9036,  423, 4983, 6682, 2783, 9432, 8991, 8251, 8690, 7419,  220,
       1658, 2217, 4102, 3397, 8042, 5055, 9715, 6139,  586, 5074, 7659,
       8722, 6354, 9553, 9822, 5016, 2687, 9987, 5430, 9777, 9455,   45,
        304, 1572, 5938, 4876, 3815, 8694, 1908, 33

In [157]:
new_arr.shape

(1000,)