In [2]:
import numpy as np

# Exercise 1: Thao tác cơ bản

- Tạo mảng 1 chiều $x$ gồm n số thực
- Chọn 3 hàm số tuỳ ý $f_1(x)$, $f_2(x)$, $f_3(x)$. Tạo 3 mảng bằng cách truyền $x$ vào trong 3 hàm số.
- Ghép bốn mảng một chiều thành một mảng hai chiều kích thước $n\times4$

In [3]:
x = np.random.randint(1,10, 10)

y1 = 3 * x + 8
y2 = 2 * x + 1
y3 = 7 * x + 9
print(x)
print(y1)
print(y2)
print(y3)







[6 1 3 2 7 7 9 7 4 4]
[26 11 17 14 29 29 35 29 20 20]
[13  3  7  5 15 15 19 15  9  9]
[51 16 30 23 58 58 72 58 37 37]


In [4]:
a = np.concatenate((x,y1))
a

array([ 6,  1,  3,  2,  7,  7,  9,  7,  4,  4, 26, 11, 17, 14, 29, 29, 35,
       29, 20, 20])

In [5]:
b = np.concatenate((y2,y3))
b

array([13,  3,  7,  5, 15, 15, 19, 15,  9,  9, 51, 16, 30, 23, 58, 58, 72,
       58, 37, 37])

In [6]:
c = np.vstack((a,b))
print (c)
print(c.shape)

[[ 6  1  3  2  7  7  9  7  4  4 26 11 17 14 29 29 35 29 20 20]
 [13  3  7  5 15 15 19 15  9  9 51 16 30 23 58 58 72 58 37 37]]
(2, 20)


## Bài tập 2: Thống kê cơ bản


- Tải dữ liệu file `heart_rate.txt` vào trong mảng `a`
- Thực hiện mô tả thống kê với các biến `Time` và `Heart Rate`: Cỡ mẫu, trung bình, trung vị, độ lệch chuẩn, giá trị lớn nhất, nhỏ nhất, phần tư Q1, Q2 và Q3

In [7]:
data = np.loadtxt('heart_rate.txt', delimiter=',', usecols=(0,1), skiprows=1, dtype='float')
data

array([[   0.,  103.],
       [   5.,  103.],
       [  10.,  103.],
       [  15.,  105.],
       [  20.,  108.],
       [  25.,  110.],
       [  30.,  110.],
       [  35.,  112.],
       [  40.,  112.],
       [  45.,  114.],
       [  50.,  114.],
       [  55.,  117.],
       [  60.,  117.],
       [  65.,  118.],
       [  70.,  119.],
       [  75.,  119.],
       [  80.,  120.],
       [  85.,  121.],
       [  90.,  121.],
       [  95.,  122.],
       [ 100.,  123.],
       [ 105.,  124.],
       [ 110.,  124.],
       [ 115.,  125.],
       [ 120.,  126.],
       [ 125.,  127.],
       [ 130.,  128.],
       [ 135.,  127.],
       [ 140.,  128.],
       [ 145.,  128.],
       [ 150.,  129.],
       [ 155.,  129.],
       [ 160.,  130.],
       [ 165.,  131.],
       [ 170.,  132.],
       [ 175.,  132.],
       [ 180.,  132.],
       [ 185.,  133.],
       [ 190.,  134.],
       [ 195.,  135.],
       [ 200.,  135.],
       [ 205.,  135.],
       [ 210.,  135.],
       [ 21

In [8]:
t_data = data[:,0]
h_data = data[:,1]

In [9]:
# mean
mean_time = np.mean(t_data)
mean_heart_rate = np.mean(h_data)
print(mean_time)
print(mean_heart_rate)

600.0
142.98340248962654


In [10]:
# median
median_time = np.median(t_data)
median_heart_rate = np.median(h_data)
print(median_time)
print(median_heart_rate)

600.0
147.0


In [11]:
# Standard Deviation
std_time = np.std(t_data)
std_heart_rate = np.std(h_data)
print(std_time)
print(std_heart_rate)

347.85054261852173
11.36346581057221


In [12]:
# Min max with Time
print('Gia tri nho nhat :', t_data.min())
print('Gia tri lon nhat :', t_data.max())


Gia tri nho nhat : 0.0
Gia tri lon nhat : 1200.0


In [13]:
# Min max with Heart Rate
print('Gia tri nho nhat :', h_data.min())
print('Gia tri lon nhat :', h_data.max())

Gia tri nho nhat : 103.0
Gia tri lon nhat : 154.0


In [14]:
# Quartiles
#Time
print("Q1 = : ", np.quantile(t_data, 0.25))
print("Q2 = : ", np.quantile(t_data, 0.5))
print("Q3 = : ", np.quantile(t_data, 0.75))

Q1 = :  300.0
Q2 = :  600.0
Q3 = :  900.0


In [15]:
# Heart Rate
print("Q1 = : ", np.quantile(h_data, 0.25))
print("Q2 = : ", np.quantile(h_data, 0.5))
print("Q3 = : ", np.quantile(h_data, 0.75))

Q1 = :  138.0
Q2 = :  147.0
Q3 = :  151.0


## Bài tập 3: Thao tác với mảng

- Tạo một mảng 2-chiều `a` cỡ $m\times n$
- Các phần tử hàng đầu tiên chạy từ `1` $\longrightarrow$ `n`
- Các phần tử cột đầu tiên nhận giá trị bằng `1`
- Các phần tử cột cuối cùng nhận giá trị bằng `n`
- Các phần tử còn lại tính theo mô tả sau
  

![Phần tử hàng dưới bằng trung bình ba phần tử xung quanh ở hàng trên](image.png)

In [16]:
a = np.ones((5,6), dtype=int) 
a[:,0]=1
a[:,-1]=6
a[0,:] = np.arange(1,7)
a


array([[1, 2, 3, 4, 5, 6],
       [1, 1, 1, 1, 1, 6],
       [1, 1, 1, 1, 1, 6],
       [1, 1, 1, 1, 1, 6],
       [1, 1, 1, 1, 1, 6]])

In [17]:
def new_arr(m,n):
    a = np.ones((m,n), dtype=float) 
    a[:,0]=1 # Các phần tử cột đầu tiên nhận giá trị bằng 1
    a[:,-1]= n # Các phần tử cột cuối cùng nhận giá trị bằng n
    a[0,:] = np.arange(1,n+1) # Các phần tử hàng đầu tiên chạy từ 1 -> n
    
    # trường hợp hàng đầu tiên là các số ngẫu nghiên
    # a[0,1:-1] = np.random.randint(1,n, (1,n-2))   
    for i in range(m-1):
        for j in range (n-2):
            a[i+1,j+1] = a[i,j:j+3].mean()
    return a
arr = new_arr(8,9)  
arr         

array([[1., 2., 3., 4., 5., 6., 7., 8., 9.],
       [1., 2., 3., 4., 5., 6., 7., 8., 9.],
       [1., 2., 3., 4., 5., 6., 7., 8., 9.],
       [1., 2., 3., 4., 5., 6., 7., 8., 9.],
       [1., 2., 3., 4., 5., 6., 7., 8., 9.],
       [1., 2., 3., 4., 5., 6., 7., 8., 9.],
       [1., 2., 3., 4., 5., 6., 7., 8., 9.],
       [1., 2., 3., 4., 5., 6., 7., 8., 9.]])